apiVersion: v1
kind: Service
metadata:
    prometheus.io/scrape: "true"
  labels:
    name: prometheus
  name: prometheus
  namespace: monitoring
spec:
  ports:
  - name: prometheus
    nodePort: 31090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  sessionAffinity: None
  type: NodePort
