---
apiVersion: v1
kind: Pod
metadata:
  name: docker-kill
  labels:
    app: docker-kill
    name: docker-kill
spec:
  nodeName: gke-cluster-2-default-pool-559f6e5b-1tlw
  restartPolicy: Never
  containers:
  - name: docker-kill
    image: ubuntu:16.04
    command: ["/bin/bash"]
    args:
    - -c
    - sleep 10; echo injecting_docker_crash..; systemctl stop docker && sleep 120 && systemctl start docker; echo reverted_docker_crash                                                      ..; exit 0
    resources:
      requests:
        cpu: 10m
        memory: 5M
      limits:
        cpu: 100m
        memory: 20M
    volumeMounts:
      - name: bus
        mountPath: /var/run
      - name: root
        mountPath: /node
    securityContext:
      privileged: true
    tty: true
  volumes:
    - name: bus
      hostPath:
        path: /var/run
    - name: root
      hostPath:
        path: /
        type: ""
